require('dotenv').config()
const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
const rateLimit = require('express-rate-limit')
const { connectDatabase } = require('./config/database')
const { errorHandler, notFound } = require('./middleware/errors')
const authRoutes = require('./routes/auth.routes')
const inventoryRoutes = require('./routes/inventory.routes')
const analyticsRoutes = require('./routes/analytics.routes')
const aiRoutes = require('./routes/ai.routes')
const operationsRoutes = require('./routes/operations.routes')

const app = express()
app.use(helmet())
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }))
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 200, standardHeaders: 'draft-8', legacyHeaders: false }))
app.use(express.json({ limit: '1mb' }))
app.get('/api/v1/health', (_req, res) => res.json({ success: true, data: { status: 'healthy', database: require('mongoose').connection.readyState === 1 ? 'connected' : 'disconnected' } }))
app.use('/api/v1/auth', authRoutes)
app.use('/api/v1/inventory', inventoryRoutes)
app.use('/api/v1/analytics', analyticsRoutes)
app.use('/api/v1/ai', aiRoutes)
app.use('/api/v1/operations', operationsRoutes)
app.use(notFound); app.use(errorHandler)
const port = process.env.PORT || 5000
connectDatabase().then(() => app.listen(port, () => console.log(`API listening on ${port}`))).catch(err => { console.error(err); process.exit(1) })
