import { useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useData } from '../context/DataContext'

export function DemandForecastingPage({ addToast }) {
  const { forecasts, generateForecast } = useData(); const [category,setCategory]=useState('Consumables'); const [loading,setLoading]=useState(false)
  const forecast=forecasts.find(record=>record.category===category)
  const run=async()=>{setLoading(true);try{await generateForecast(category);addToast('Forecast generated','A persisted forecast is ready for review.','success')}catch(error){addToast('Forecast unavailable',error.response?.data?.error?.message||'Unable to generate a forecast.','error')}finally{setLoading(false)}}
  return <div><div className="filter-bar" style={{justifyContent:'space-between'}}><div className="filter-group"><label>Category:</label><select className="form-select" value={category} onChange={e=>setCategory(e.target.value)}><option>Tapes</option><option>Braces</option><option>Consumables</option><option>Therapy Accessories</option><option>Hygiene Supplies</option></select></div><button className="btn-primary" onClick={run} disabled={loading}>{loading?'Generating…':'Run demand forecast'}</button></div>{loading?<div className="panel" style={{textAlign:'center',padding:60}}><div className="loading-spinner"/><p>Preparing forecast from persisted inventory data…</p></div>:!forecast?<div className="empty panel"><h2>No forecast yet</h2><p>Run a forecast after creating inventory records for this category.</p></div>:<div style={{display:'grid',gridTemplateColumns:'2fr 1fr',gap:22}}><div className="panel"><div className="panel-head"><div><h2>Demand Forecast — {forecast.category}</h2><p>{forecast.modelVersion} · {new Date(forecast.createdAt).toLocaleString()}</p></div><span className="priority medium">Confidence {Math.round(forecast.confidence*100)}%</span></div><ResponsiveContainer width="100%" height={260}><AreaChart data={forecast.periods}><CartesianGrid vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Area dataKey="actual" stroke="#94a3b8" fill="#f1f5f9"/><Area dataKey="forecast" stroke="#4f46e5" fill="#e0e7ff"/></AreaChart></ResponsiveContainer></div><div className="panel"><h2>Inputs & source snapshot</h2>{forecast.inputs.map(input=><p key={input} style={{fontSize:12}}>{input}</p>)}<small>Source records: {forecast.sourceSnapshot?.items?.length||0}</small><p style={{fontSize:12}}>Interval: {forecast.periods?.[3]?.lower}–{forecast.periods?.[3]?.upper} units next month.</p></div></div>}</div>
}
